spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/products?currentSchema=products
    username: postgres
    password: postgrespw
  liquibase:
    contexts: dev
    change-log: classpath:db/master-changelog.yml
    url: jdbc:postgresql://localhost:5432/products?currentSchema=products
    user: postgres
    password: postgrespw
    enabled: true