spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/products?currentSchema=products
    username: postgres
    password: postgrespw
  liquibase:
    contexts: prod
    change-log: classpath:db/master-changelog.yml
    url: jdbc:postgresql://postgres:5432/products?currentSchema=products
    user: postgres
    password: postgrespw
    enabled: true