spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/products?currentSchema=products
    username: postgres
    password: postgrespw
  liquibase:
    change-log: classpath:db/master-changelog.yml
    enabled: true